name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: '0 18 * * *'

jobs:

  lint:
    runs-on: ubuntu-latest
    env:
      python-version: "3.11"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Lint with flake8
        run: flake8 --ignore=E501,E722,W503,E203,F405,F403,F401,E704 semantipy tests

      - name: Check black formatting
        run: black semantipy tests --check --line-length=120
        if: success() || failure()

  test:

    runs-on: ubuntu-latest
    env:
      python-version: "3.10"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Test with pytest
        env:
          AZURE_ENDPOINT: ${{ secrets.AZURE_ENDPOINT }}
          AZURE_API_KEY: ${{ secrets.AZURE_API_KEY }}
          AZURE_DEPLOYMENT: ${{ secrets.AZURE_DEPLOYMENT }}
        run: |
          cd tests
          pytest .
